2023-03-27 13:39:22,799 INFO    MainThread:2066019 [wandb_setup.py:_flush():71] setting env: {}
2023-03-27 13:39:22,799 INFO    MainThread:2066019 [wandb_setup.py:_flush():71] setting login settings: {}
2023-03-27 13:39:22,799 INFO    MainThread:2066019 [wandb_init.py:_log_setup():357] Logging user logs to /home/soheil/DRL-Bench/drl/testjax/wandb/run-20230327_133922-9rj1rg6u/logs/debug.log
2023-03-27 13:39:22,799 INFO    MainThread:2066019 [wandb_init.py:_log_setup():358] Logging internal logs to /home/soheil/DRL-Bench/drl/testjax/wandb/run-20230327_133922-9rj1rg6u/logs/debug-internal.log
2023-03-27 13:39:22,799 INFO    MainThread:2066019 [wandb_init.py:init():390] calling init triggers
2023-03-27 13:39:22,799 INFO    MainThread:2066019 [wandb_init.py:init():395] wandb.init called with sweep_config: {}
config: {}
2023-03-27 13:39:22,799 INFO    MainThread:2066019 [wandb_init.py:init():435] starting backend
2023-03-27 13:39:22,799 INFO    MainThread:2066019 [backend.py:_multiprocessing_setup():94] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-03-27 13:39:22,805 INFO    MainThread:2066019 [backend.py:ensure_launched():198] starting backend process...
2023-03-27 13:39:22,806 INFO    MainThread:2066019 [backend.py:ensure_launched():203] started backend process with pid: 2067073
2023-03-27 13:39:22,806 INFO    MainThread:2066019 [wandb_init.py:init():444] backend started and connected
2023-03-27 13:39:22,807 INFO    MainThread:2066019 [wandb_init.py:init():503] updated telemetry
2023-03-27 13:39:22,810 INFO    MainThread:2066019 [wandb_init.py:init():533] communicating current version
2023-03-27 13:39:23,303 INFO    MainThread:2066019 [wandb_init.py:init():538] got version response upgrade_message: "wandb version 0.14.0 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-03-27 13:39:23,303 INFO    MainThread:2066019 [wandb_init.py:init():548] communicating run to backend with 30 second timeout
2023-03-27 13:39:51,258 WARNING MainThread:2066019 [wandb_init.py:init():891] interrupted
Traceback (most recent call last):
  File "/home/soheil/miniconda3/envs/bench/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 870, in init
    run = wi.init()
  File "/home/soheil/miniconda3/envs/bench/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 549, in init
    ret = backend.interface.communicate_run(run, timeout=30)
  File "/home/soheil/miniconda3/envs/bench/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 210, in communicate_run
    return self._communicate_run(run, timeout=timeout)
  File "/home/soheil/miniconda3/envs/bench/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 901, in _communicate_run
    resp = self._communicate(req, timeout=timeout)
  File "/home/soheil/miniconda3/envs/bench/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 799, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/soheil/miniconda3/envs/bench/lib/python3.10/site-packages/wandb/sdk/interface/router.py", line 32, in get
    is_set = self._object_ready.wait(timeout)
  File "/home/soheil/miniconda3/envs/bench/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/home/soheil/miniconda3/envs/bench/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
